require 'tempfile'
require 'hamster'
require 'open3'

require 'pilot-gnuplot/version'
require 'pilot-gnuplot/staff/settings'
require 'pilot-gnuplot/mixins/option_handling'
require 'pilot-gnuplot/mixins/error_handling'
require 'pilot-gnuplot/mixins/plottable'
require 'pilot-gnuplot/mixins/external_classes'
require 'pilot-gnuplot/staff/terminal'
require 'pilot-gnuplot/staff/datablock'
require 'pilot-gnuplot/staff/dataset'
require 'pilot-gnuplot/plot'
require 'pilot-gnuplot/splot'
require 'pilot-gnuplot/multiplot'
