require 'tempfile'
require 'hamster'
require 'open3'

require 'pilot-gnuplot/version'
require 'pilot-gnuplot/helpers/settings'
require 'pilot-gnuplot/helpers/options_helper'
require 'pilot-gnuplot/helpers/error_handler'
require 'pilot-gnuplot/terminal'
require 'pilot-gnuplot/datablock'
require 'pilot-gnuplot/dataset'
require 'pilot-gnuplot/plot'
require 'pilot-gnuplot/splot'
require 'pilot-gnuplot/multiplot'
require 'pilot-gnuplot/mixins'
